# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit app code into the container
COPY app.py /app/
COPY flask_app.py /flask_app/

# Install required packages
RUN pip install requirements.txt

# Expose the Streamlit port
EXPOSE 8501
EXPOSE 5000
CMD ["python", "flask_app.py"]
# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py"]
